linear-regression:
		cd regression && python linear_regression.py > reg.txt
		cd regression && open reg.txt


allClassification:

		#cd classification && cd all_classification && python breast_cancer.py > classification.txt

		#cd classification && cd all_classification && open classification.txt

decision-tree:
		cd classification && cd decision-tree && python decision_tree.py > tree.txt
		cd classification && cd decision-tree && open tree.txt


random-forest:
		cd classification && cd random-forest && python random_forest.py > rf.txt
		cd classification && cd random-forest && open rf.txt



logistic-reg:
		cd classification && cd logistic-regression && python logistic_regression.py > logistic.txt
		cd classification && cd logistic-regression && open logistic.txt


cluster:
		cd clustering && python k_clustering.py > clustering.txt
		cd clustering && open clustering.txt

recommendation:
		cd recommendations && python recommender_sysytem.py > recommendation.txt
		cd recommendations && open recommendation.txt
